TRAIN_FILE_V2 = 'train_metadata.csv'
TEST_FILE_V2 = 'test_metadata.csv'
INFO_FILE_V2 = 'split_info.json'


PATH_ARTIFACTS_V2 = './artifacts_v2/'
SAMPLE_METADATA_FILE_V2=f'{PATH_ARTIFACTS_V2}/dataset/sampled_metadata.csv'
CLASS_WEIGHTS_FILE_V2=f'{PATH_ARTIFACTS_V2}/dataset/class_weights.json'
CLASS_AGRESSIVE_WEIGHTS_FILE_V2=f'{PATH_ARTIFACTS_V2}/dataset/class_weights_aggressive.json'

PATH_DATASETS_V2 = './artifacts_v2/datasets/'


FEATURE_EXTRACTOR_OUTPUT_DIR_V2 = f'{PATH_ARTIFACTS_V2}/feature_extractor/'#pkl
FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2 = f'{FEATURE_EXTRACTOR_OUTPUT_DIR_V2}/features'
MODEL_OUTPUT_DIR_V2 = f'{PATH_ARTIFACTS_V2}/models/'

X_TRAIN_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/X_train.npy'
Y_TRAIN_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/y_train.npy'
X_TEST_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/X_test.npy'
Y_TEST_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/y_test.npy'


CLASS_NAMES_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/class_names.json'
FEATURE_NAMES_FILE_V2 = f'{FEATURE_EXTRACTOR_FEATURES_OUTPUT_DIR_V2}/feature_names.json'


REPORTS_DIR_V2 = f'{PATH_ARTIFACTS_V2}/reports/'
REPORT_XGBOOST_CONFUSION_MATRIX_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_confusion_matrix.png'
REPORT_XGBOOST_FEATURE_IMPORTANCE_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_feature_importance.png'
REPORT_XGBOOST_CLASSIFICATION_REPORT_FILE = f'{REPORTS_DIR_V2}/xgboost_classification_report.txt'
REPORT_XGBOOST_MODEL_FILE_V2 = f'{MODEL_OUTPUT_DIR_V2}/xgboost_model.pkl'
REPORT_XGBOOST_METRICS_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_metrics.json'

REPORT_LOGREG_CONFUSION_MATRIX_FILE_V2=f'{REPORTS_DIR_V2}/logreg_confusion_matrix.png'
REPORT_LOGREG_COEFFICIENTS_FILE_V2=f'{REPORTS_DIR_V2}/logreg_coefficients_'
REPORT_LOGREG_CLASSIFICATION_REPORT_FILE_V2=f'{REPORTS_DIR_V2}/logreg_classification_report.txt'
REPORT_LOGREG_MODEL_FILE_V2=f'{MODEL_OUTPUT_DIR_V2}/logreg_model.pkl'
REPORT_LOGREG_METRICS_FILE_V2=f'{REPORTS_DIR_V2}/logreg_metrics.json'
REPORT_MODEL_COMPARISON_V2=f'{REPORTS_DIR_V2}/model_comparison.csv'
BEST_MODEL_FILE_V2=f'{MODEL_OUTPUT_DIR_V2}/best_model.pkl'
TARGET_COLUMN_V2 = 'main_category'


REPORTS_DIR_V2 = f'{PATH_ARTIFACTS_V2}/reports/'
REPORT_XGBOOST_CONFUSION_MATRIX_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_confusion_matrix.png'
REPORT_XGBOOST_FEATURE_IMPORTANCE_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_feature_importance.png'
REPORT_XGBOOST_CLASSIFICATION_REPORT_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_classification_report.txt'
REPORT_XGBOOST_MODEL_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_model.pkl'
REPORT_XGBOOST_METRICS_FILE_V2 = f'{REPORTS_DIR_V2}/xgboost_metrics.json'